# This is a basic workflow to help you get started with Actions

name: CI Coveralls

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main", "developer"]
  pull_request:
    branches: ["main", "developer"]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:     
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: use yarn
        run: npm install -g yarn

      - name: npm install, yarn storybook
        run: |
          npm install
          yarn storybook

      -name: yarn test-storybook --coverage, yarn test-storybook
        run: |
          yarn test-storybook --coverage
          yarn test-storybook

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
